[package]
name = "rabbit-offline"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.30"
regex = "1.10.6"
reqwest = "0.12.7"
tokio = {version = "1.40.0", features = ["full"]}
